### ISSUE TITLE
UI buttons show wrong state in case of a page refresh during a flash.

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Reflash#20]
As discussed on Discord in #support-recore on 23 Aug. 2022, if the Reflash page is refreshed during a flash, the Cancel button doesn't appear and the Install button is shown again instead.

This can lead to simultaneous flash commands being launched, which will cause issues.

**Comment by eliasbakken** [comment]
In main there is now a fix for this. It does not work for "upload file"
